### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by applibs** [devlabnet/cssanim#1]
Always i got error:
Uncaught TypeError: Cannot read property 'querySelector' of undefined
CKEDITOR.plugins.cssanim.getCustomCss @ plugin.js?t=FACH:1085(anonymous function) @ plugin.js?t=FACH:368q @ ckeditor.js?v=kaim:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js?v=kaim:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js?v=kaim:13(anonymous function) @ ckeditor.js?v=kaim:829(anonymous function) @ ckeditor.js?v=kaim:28

**Comment by EvoWebFrance** [comment]
Same problem : always have an error in plugins.js line 1159 : 
`TypeError: obj is undefined`
`divRes = obj.querySelector("#cssResultsDiv");`

**Comment by cricri042** [comment]
Normally fixed by the last commit, can you try it ?
Normalement fixé par le dernier commit, pouvez vous tester ?
I didn't did the update on ckeditor site as I get some problem to upload the new version of the plugin, so please test the plugin with the files on github.

  --Christian

**Comment by cricri042** [comment]
Normally version 1.6 on ckeditor.com is also updated !
Have fun

--Christian

**Comment by EvoWebFrance** [comment]
Hello,
This new version is ok, no error left ! Thanks
C'est ok, plus d'erreur ! Merci

--Olivier
