### ISSUE TITLE
Left or right click selects the whole line in Firefox

### ISSUE THREAD

**Issue by initiafy-kelvin** [devlabnet/cssanim#2]
When I click anywhere in the editor content with Firefox, the whole line of text is selected, rather than the cursor being placed at the location I clicked. I then have to use the keyboard's arrow keys to place the cursor at the desired location.

This is reproducible in the online demo at http://devlabnet.eu/softdev/cssanim/web/demo.php using Firefox 43.0.1 on Windows 8.1

![image](https://cloud.githubusercontent.com/assets/16384961/11931311/6bd59ade-a7e3-11e5-94a6-5563f06bc67f.png)

**Comment by cricri042** [comment]
Hi Kelvin,

Can you try the new version (1.3).

Hopping this will fix teh problem.

  --Christian

**Comment by initiafy-kelvin** [comment]
Confirmed resolved, thank you!
